// This file is auto-generated by @hey-api/openapi-ts

export const $CreateTaskBody = {
    additionalProperties: false,
    type: 'object',
    properties: {
        name: {
            minLength: 1,
            maxLength: 100,
            type: 'string'
        },
        description: {
            maxLength: 1000,
            default: '',
            type: 'string'
        },
        dueDate: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: ['name']
} as const;

export const $CreateTaskResponse = {
    additionalProperties: false,
    type: 'object',
    properties: {
        ok: {
            const: true,
            type: 'boolean'
        },
        data: {
            additionalProperties: false,
            type: 'object',
            properties: {
                task: {
                    additionalProperties: false,
                    type: 'object',
                    properties: {
                        id: {
                            minLength: 24,
                            maxLength: 24,
                            pattern: '^[a-fA-F0-9]{24}$',
                            description: 'MongoDB ObjectID',
                            type: 'string'
                        },
                        name: {
                            minLength: 1,
                            maxLength: 100,
                            type: 'string'
                        },
                        description: {
                            maxLength: 1000,
                            default: '',
                            type: 'string'
                        },
                        dueDate: {
                            type: 'Date'
                        },
                        status: {
                            anyOf: [
                                {
                                    const: 0,
                                    type: 'number'
                                },
                                {
                                    const: 1,
                                    type: 'number'
                                },
                                {
                                    const: 2,
                                    type: 'number'
                                }
                            ]
                        },
                        createdAt: {
                            type: 'Date'
                        }
                    },
                    required: ['id', 'name', 'status', 'createdAt']
                }
            },
            required: ['task']
        }
    },
    required: ['ok', 'data']
} as const;

export const $GetTaskResponse = {
    additionalProperties: false,
    type: 'object',
    properties: {
        ok: {
            const: true,
            type: 'boolean'
        },
        data: {
            additionalProperties: false,
            type: 'object',
            properties: {
                task: {
                    additionalProperties: false,
                    type: 'object',
                    properties: {
                        id: {
                            minLength: 24,
                            maxLength: 24,
                            pattern: '^[a-fA-F0-9]{24}$',
                            description: 'MongoDB ObjectID',
                            type: 'string'
                        },
                        name: {
                            minLength: 1,
                            maxLength: 100,
                            type: 'string'
                        },
                        description: {
                            maxLength: 1000,
                            default: '',
                            type: 'string'
                        },
                        dueDate: {
                            type: 'Date'
                        },
                        status: {
                            anyOf: [
                                {
                                    const: 0,
                                    type: 'number'
                                },
                                {
                                    const: 1,
                                    type: 'number'
                                },
                                {
                                    const: 2,
                                    type: 'number'
                                }
                            ]
                        },
                        createdAt: {
                            type: 'Date'
                        }
                    },
                    required: ['id', 'name', 'status', 'createdAt']
                }
            },
            required: ['task']
        }
    },
    required: ['ok', 'data']
} as const;

export const $UpdateTaskBody = {
    type: 'object',
    properties: {
        name: {
            minLength: 1,
            maxLength: 100,
            type: 'string'
        },
        description: {
            maxLength: 1000,
            default: '',
            type: 'string'
        },
        dueDate: {
            description: 'Field to update due date. Remove from db if null',
            anyOf: [
                {
                    type: 'null'
                },
                {
                    format: 'date-time',
                    type: 'string'
                }
            ]
        }
    }
} as const;

export const $UpdateTaskResponse = {
    additionalProperties: false,
    type: 'object',
    properties: {
        ok: {
            const: true,
            type: 'boolean'
        },
        data: {
            additionalProperties: false,
            type: 'object',
            properties: {
                task: {
                    additionalProperties: false,
                    type: 'object',
                    properties: {
                        id: {
                            minLength: 24,
                            maxLength: 24,
                            pattern: '^[a-fA-F0-9]{24}$',
                            description: 'MongoDB ObjectID',
                            type: 'string'
                        },
                        name: {
                            minLength: 1,
                            maxLength: 100,
                            type: 'string'
                        },
                        description: {
                            maxLength: 1000,
                            default: '',
                            type: 'string'
                        },
                        dueDate: {
                            type: 'Date'
                        },
                        status: {
                            anyOf: [
                                {
                                    const: 0,
                                    type: 'number'
                                },
                                {
                                    const: 1,
                                    type: 'number'
                                },
                                {
                                    const: 2,
                                    type: 'number'
                                }
                            ]
                        },
                        createdAt: {
                            type: 'Date'
                        }
                    },
                    required: ['id', 'name', 'status', 'createdAt']
                }
            },
            required: ['task']
        }
    },
    required: ['ok', 'data']
} as const;

export const $DeleteTaskResponse = {
    additionalProperties: false,
    type: 'object',
    properties: {
        ok: {
            const: true,
            type: 'boolean'
        },
        data: {
            additionalProperties: false,
            type: 'object',
            properties: {
                taskId: {
                    minLength: 24,
                    maxLength: 24,
                    pattern: '^[a-fA-F0-9]{24}$',
                    description: 'MongoDB ObjectID',
                    type: 'string'
                }
            },
            required: ['taskId']
        }
    },
    required: ['ok', 'data']
} as const;

export const $GetTasksResponse = {
    additionalProperties: false,
    type: 'object',
    properties: {
        ok: {
            const: true,
            type: 'boolean'
        },
        data: {
            additionalProperties: false,
            type: 'object',
            properties: {
                tasks: {
                    type: 'array',
                    items: {
                        additionalProperties: false,
                        type: 'object',
                        properties: {
                            id: {
                                minLength: 24,
                                maxLength: 24,
                                pattern: '^[a-fA-F0-9]{24}$',
                                description: 'MongoDB ObjectID',
                                type: 'string'
                            },
                            name: {
                                minLength: 1,
                                maxLength: 100,
                                type: 'string'
                            },
                            description: {
                                maxLength: 1000,
                                default: '',
                                type: 'string'
                            },
                            dueDate: {
                                type: 'Date'
                            },
                            status: {
                                anyOf: [
                                    {
                                        const: 0,
                                        type: 'number'
                                    },
                                    {
                                        const: 1,
                                        type: 'number'
                                    },
                                    {
                                        const: 2,
                                        type: 'number'
                                    }
                                ]
                            },
                            createdAt: {
                                type: 'Date'
                            }
                        },
                        required: ['id', 'name', 'status', 'createdAt']
                    }
                }
            },
            required: ['tasks']
        }
    },
    required: ['ok', 'data']
} as const;