// This file is auto-generated by @hey-api/openapi-ts

export type CreateTaskBody = {
    name: string;
    description?: string;
    dueDate?: string;
};

export type CreateTaskResponse = {
    ok: true;
    data: {
        task: {
            /**
             * MongoDB ObjectID
             */
            id: string;
            name: string;
            description?: string;
            dueDate?: Date;
            status: 0 | 1 | 2;
            createdAt: Date;
        };
    };
};

export type GetTaskResponse = {
    ok: true;
    data: {
        task: {
            /**
             * MongoDB ObjectID
             */
            id: string;
            name: string;
            description?: string;
            dueDate?: Date;
            status: 0 | 1 | 2;
            createdAt: Date;
        };
    };
};

export type UpdateTaskBody = {
    name?: string;
    description?: string;
    /**
     * Field to update due date. Remove from db if null
     */
    dueDate?: null | string;
};

export type UpdateTaskResponse = {
    ok: true;
    data: {
        task: {
            /**
             * MongoDB ObjectID
             */
            id: string;
            name: string;
            description?: string;
            dueDate?: Date;
            status: 0 | 1 | 2;
            createdAt: Date;
        };
    };
};

export type DeleteTaskResponse = {
    ok: true;
    data: {
        /**
         * MongoDB ObjectID
         */
        taskId: string;
    };
};

export type GetTasksResponse = {
    ok: true;
    data: {
        tasks: Array<{
            /**
             * MongoDB ObjectID
             */
            id: string;
            name: string;
            description?: string;
            dueDate?: Date;
            status: 0 | 1 | 2;
            createdAt: Date;
        }>;
    };
};

export type TaskControllerCreateTaskData = {
    requestBody: CreateTaskBody;
};

export type TaskControllerCreateTaskResponse = CreateTaskResponse;

export type TaskControllerGetTaskData = {
    id: string;
};

export type TaskControllerGetTaskResponse = GetTaskResponse;

export type TaskControllerUpdateTaskData = {
    id: string;
    requestBody: UpdateTaskBody;
};

export type TaskControllerUpdateTaskResponse = UpdateTaskResponse;

export type TaskControllerDeleteTaskData = {
    id: string;
};

export type TaskControllerDeleteTaskResponse = DeleteTaskResponse;

export type TasksControllerGetTasksData = {
    query?: string;
    sortBy?: "createdAt" | "updatedAt" | "dueDate";
    sortOrder?: "asc" | "desc";
};

export type TasksControllerGetTasksResponse = GetTasksResponse;

export type $OpenApiTs = {
    '/api/v1/task': {
        post: {
            req: TaskControllerCreateTaskData;
            res: {
                200: CreateTaskResponse;
            };
        };
    };
    '/api/v1/task/{id}': {
        get: {
            req: TaskControllerGetTaskData;
            res: {
                200: GetTaskResponse;
            };
        };
        patch: {
            req: TaskControllerUpdateTaskData;
            res: {
                200: UpdateTaskResponse;
            };
        };
        delete: {
            req: TaskControllerDeleteTaskData;
            res: {
                200: DeleteTaskResponse;
            };
        };
    };
    '/api/v1/tasks': {
        get: {
            req: TasksControllerGetTasksData;
            res: {
                200: GetTasksResponse;
            };
        };
    };
};